4.1 NumPy的ndarry，一种多维数组对象

In [19]:
import numpy as np
#有些库的函数名可能与 NumPy 的函数名相同
#.randn()：这是 np.random 模块中的一个核心函数。功能：它从标准正态分布

In [20]:
data = np.random.randn(2,3)
data

array([[ 1.17738537,  2.46741925, -0.35129898],
       [ 0.17862241,  1.54627748,  0.44509762]])

数学运算

In [21]:
data * 10

array([[11.77385365, 24.67419254, -3.51298983],
       [ 1.78622413, 15.46277484,  4.4509762 ]])

In [22]:
data + data

array([[ 2.35477073,  4.93483851, -0.70259797],
       [ 0.35724483,  3.09255497,  0.89019524]])

In [23]:
data.shape #shape告诉我们数组的结构

(2, 3)

In [24]:
data.dtype #dtype告诉我们数组里面元素的数据类型

dtype('float64')

创建ndarray，使用array函数。np.array() 是 NumPy 库中最常用、最核心的函数之一。它的主要作用是：

将 Python 中的列表 (list)、元组 (tuple) 或任何序列数据，转换成 NumPy 的多维数组 (ndarray)。

In [25]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

🧐 核心原因：数据类型向上兼容
当您使用 np.array() 创建数组时，NumPy 必须确保数组中的所有元素都具有相同的单一数据类型。

输入列表分析： 您的 data1 = [6, 7.5, 8, 0, 1] 包含：

整数：6、8、0、1

浮点数： 7.5

NumPy 的处理：

NumPy 发现列表中同时有整数和浮点数。

由于浮点数（例如 7.5）比整数（例如 6）具有更高的精度和更广的表示范围，NumPy 必须将所有元素都转换成能容纳最高精度的那个类型。

整数可以完美地表示为浮点数（例如 6 变成 6.0），但浮点数无法在不损失精度的情况下表示为整数（例如 7.5 变成 7 就会丢失 .5）。

结果： 为了避免数据丢失，NumPy 将整个数组的 数据类型 (dtype) 向上兼容，统一提升为 浮点数类型。

因此，输出的 arr1 变成了 [6.0, 7.5, 8.0, 0.0, 1.0]，并且其 dtype 为 float64 (64位浮点数)。

In [26]:
#嵌套序列（比如一组等长的列表组成的列表）将会变成一个多维数组

In [27]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
arr2.ndim
#矩阵的维度

2

![维度举例](维度解释.png)

就是 NumPy 告诉 “沿着哪个方向进行计算” 的关键指令

In [29]:
arr2.shape
#shape显示元组中的每个数字都精确地告诉您该维度（轴）上有多少元素

(2, 4)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int64')

In [32]:
np.zeros(10) #ones是创建全1的数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.empty((2,3,2))
#很多情况下np.empty会返回很多未初始化的垃圾值

array([[[1.54871229e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.06811422e-306, 3.69776220e-062]],

       [[4.22470811e-090, 1.33621712e+165],
        [1.53430554e-052, 5.54915850e+170],
        [3.99910963e+252, 2.00298098e-076]]])

In [34]:
#arrange是python内置range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

dtype 在 NumPy 中是 Data Type（数据类型）的缩写，它是 NumPy 数组 (ndarray) 中 最核心的属性之一。

💡 dtype 的核心含义
dtype 描述了数组中 每个元素 所占用的内存大小和数据种类。

简单来说，dtype 就是告诉 NumPy：“这个数组中的所有值都是什么类型的数据，以及它们应该在内存中占用多少空间。”

1. 它是统一的（Homogeneous）
这是 dtype 与 Python 列表最本质的区别：

NumPy 数组： 数组中所有元素的 dtype 必须是相同的（例如，全部是 64 位整数，或全部是 32 位浮点数）。这是 NumPy 能够进行高效矢量化计算的基础。

Python 列表： 列表可以存储混合类型（例如，一个整数、一个字符串、一个浮点数）。

2. 它是内存效率的关键
dtype 允许您精确控制数据占用的内存。例如：

如果您的数据都是 0 到 255 之间的整数（例如图像的像素值），您可以使用 np.uint8（8 位无符号整数）。

相比默认的 np.int64（64 位整数），使用 np.uint8 可以节省 8 倍 的内存空间。
astype() 是 NumPy 数组 (ndarray) 中一个非常重要的 方法，它的作用是：

强制转换数组中所有元素的数据类型（dtype）。

💡 astype() 的核心作用
当您需要将数组中的数据从一种类型（例如浮点数 float64）精确地转换成另一种类型（例如整数 int32 或布尔值 bool）时，就需要用到 astype()。

语法
Python

new_array = arr.astype(dtype, copy=True)
dtype (必需)： 您希望数组转换成的目标数据类型，可以是 NumPy 的 dtype 对象（如 np.int32）或 Python 的类型（如 int）。

1. 降级/升级数据类型
您可以利用 astype() 来优化内存使用或确保计算精度。


In [ ]:
import numpy as np

# 原始数组是浮点数 dtype=float64
arr_float = np.array([1.2, 5.8, 9.1, 0.5]) 
print(arr_float) 
# 输出: [1.2 5.8 9.1 0.5]

# 强制转换成整数 (astype(int) 或 astype(np.int32))
arr_int = arr_float.astype(int) 

print(arr_int)
# 输出: [1 5 9 0] 
# 注意：浮点数的小数点部分被直接截断（不是四舍五入）

In [16]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)

In [17]:
arr1.dtype

dtype('float64')

In [35]:
arr2.dtype

dtype('int64')